[workspace]
members = [
    "core",
    "cluster",
    "remote",
    "utils",
]

[package]
name = "nexus-actor-rs"
version = "0.19.3"
edition = "2021"
description = "Nexus Actor"
license = "MIT OR Apache-2.0"
keywords = ["actor", "async"]
categories = ["asynchronous"]
repository = "https://github.com/j5ik2o/nexus-actor-rs"

[dependencies]
async-trait = "0.1.77"
bytes = "1.5.0"
chrono = "0.4.35"
futures = "0.3.30"
futures-util = "0.3.30"
log = "0.4.21"
prost = "0.13.0"
prost-types = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
static_assertions = "1.1.0"
thiserror = "2.0.9"
tokio = { version = "1.37.0" , features = ["full"] }
tonic = "0.12.3"
tonic-types = "0.12.3"
