pub mod actor;
pub mod actor_error;
pub mod actor_handle;
pub mod actor_inner_error;
pub mod actor_process;
pub mod actor_producer;
pub mod actor_receiver;
pub mod behavior;
pub mod context_decorator;
pub mod context_decorator_chain;
pub mod context_handler;
pub mod continuer;
pub mod middleware_chain;
pub mod pid;
pub mod pid_set;
mod pid_set_test;
pub mod props;
pub mod receiver_middleware;
pub mod receiver_middleware_chain;
pub mod restart_statistics;
pub mod sender_middleware;
pub mod sender_middleware_chain;
pub mod spawn_middleware;
pub mod spawner;
pub mod taks;

// include!(concat!(env!("OUT_DIR"), "/actor.rs"));
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pid {
  #[prost(string, tag = "1")]
  pub address: ::prost::alloc::string::String,
  #[prost(string, tag = "2")]
  pub id: ::prost::alloc::string::String,
  #[prost(uint32, tag = "3")]
  pub request_id: u32,
}

/// system messages

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Touch {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Touched {
  #[prost(message, optional, tag = "1")]
  pub who: ::core::option::Option<Pid>,
}
