# docker-compose up -d
# @see https://docs.docker.com/compose/compose-file/
version: '3.4'
services:
  consul:
    container_name: dev-consul
    image: consul:1.10
    restart: unless-stopped
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0


  etcd:
    container_name: dev-etcd
    image: quay.io/coreos/etcd:v3.5.0
    restart: unless-stopped
    ports:
      - 2379:2379
      - 2380:2380
    command: >
      /usr/local/bin/etcd
        --name node1
        --data-dir=/etcd-data
        --listen-client-urls    http://0.0.0.0:2379
        --listen-peer-urls      http://0.0.0.0:2380
        --advertise-client-urls http://127.0.0.1:2379
        --initial-advertise-peer-urls http://127.0.0.1:2380
        --initial-cluster node1=http://127.0.0.1:2380
        --auto-compaction-mode=periodic 
        --auto-compaction-retention=30m

  zookeeper:
    container_name: dev-zookeeper
    image: zookeeper:3.7
    restart: unless-stopped
    ports:
      - 8000:2181
