[package]
name = "nexus-actor-cluster-rs"
version = "0.19.3"
edition = "2021"
description = "Cluster library for Nexus Actor"
license = "MIT OR Apache-2.0"
keywords = ["actor", "async"]
categories = ["asynchronous"]
repository = "https://github.com/j5ik2o/nexus-actor-rs"

[dependencies]
async-trait = "0.1.77"
bytes = "1.5.0"
dashmap = "5.5.3"
futures = "0.3.30"
log = "0.4.21"
nexus-actor-core-rs = { version = "0.*", path = "../core" }
num_enum = "0.7.2"
once_cell = "1.19.0"
prost = "0.13.0"
prost-types = "0.13"
thiserror = "2.0.9"
tokio = { version = "1.37.0" , features = ["full"] }
tonic = "0.12.3"
tonic-types = "0.12.3"
