name: Weekly Benchmarks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install protoc and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler jq

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Fetch previous benchmark history
        shell: bash
        run: |
          if git ls-remote --exit-code origin gh-pages >/dev/null 2>&1; then
            git fetch origin gh-pages
            git checkout origin/gh-pages -- benchmarks || true
          fi

      - name: Run benchmarks
        env:
          RUSTFLAGS: "-Copt-level=3"
          THRESHOLD_NS: ${{ vars.REENTRANCY_THRESHOLD_NS != '' && vars.REENTRANCY_THRESHOLD_NS || 90000000 }}
        run: cargo bench -p nexus-actor-bench-rs --bench reentrancy

      - name: Export benchmark metrics
        run: |
          mkdir -p benchmarks/history
          scripts/export_bench_metrics.py --output benchmarks/history/bench_history.csv

      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bench-history
          path: benchmarks/history/bench_history.csv

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: benchmarks
          keep_files: true
