name: remote-release
on:
  push:
    tags:
      - 'nexus-actor-remote-rs-v[0-9]+.[0-9]+.[0-9]+'
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: arduino/setup-protoc@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: release the crate
        run: |
          cargo publish --token ${{ secrets.CARGO_TOKEN }} -p nexus-actor-remote-rs --no-verify
